### ISSUE TITLE
Does not work with JPG (uppercase file extensions)

### ISSUE THREAD

**Issue by pwernette** [Doodleverse/dash_doodler#11]
I know it is a minor issue, but I could not get an image with uppercase JPG extension to show up in dash_doodler. After manually changing the file extension name to lowercase, the image did load and worked fine. I'm not sure how much it would take to accept uppercase and lowercase file extensions. Just thinking in terms of opening the utility to a broader set of imagery.

**Comment by ddbuscombe** [comment]
Yep, on my todo list - thanks for the reminder

**Comment by ddbuscombe** [comment]
fixed
