### ISSUE TITLE
User interface suggestions

### ISSUE THREAD

**Issue by csherwood-usgs** [Doodleverse/dash_doodler#2]
Here are a few suggestions for the UI:

* Need a way to track the model coefficients. Have the sliders indicate the values...and maybe offer the option of typing them in a box (so you can repeat with values you like). Or is there a table that the code can read for default values? Maybe also print them with the output.

* Maybe a button to reset the coefficients to the defaults?

* Delay running the model until all of the coefficients are adjusted...right now it jumps right into the calcs as soon a slider is moved, but maybe you want to adjust two sliders first. Maybe change the compute segmentation to a button that changes color if the model is out of date wrt to the current settings. Oh wait, I see how that works. I can uncheck it or recheck it. Still like the button idea.

* Publish the color order so people can assign colors by changing the order of the labels.

**Comment by MARDAScience** [comment]
Good ideas re 1 and 2, and should be easy enough to implement. Re 3, I need to revisit the way it runs and re-runs the calcs. I should also split things up wrt implementation of RF, then CRF. Will think .... Re 4, also a good idea. I could also explore making a few different palettes available for user to toggle

**Comment by ddbuscombe** [comment]
Published the colors in the colormap on the last push: https://github.com/dbuscombe-usgs/dash_doodler#use

**Comment by aritchie-usgs** [comment]
- A show/hide checkbox (separate from the "compute" checkbox) would be useful for "looking under" the computed layer to decide if you're happy with the computation or not without having to recompute.

- If the toolbar were vertical next to the doodle control panel it wouldn't overlap my image, which makes it hard to doodle details in the upper-right corner

- loading a new image should reset the "compute/show calc" button to unchecked state

**Comment by ddbuscombe** [comment]
suggestions 1 and 3 are great but would involve a fairly major change and likely a database backend... working on it. As for 2, I have tried to change the orientation but can't figure out how using the `dcc.Graph` framework (https://dash.plotly.com/dash-core-components/graph) tips appreciated

**Comment by csherwood-usgs** [comment]
Would it make sense to uncheck Compute/Show whenever a new figure is selected? I always forget to do that. Oh, I see Andy also suggested that.

**Comment by ddbuscombe** [comment]
FYI I'm working on a version that just has a big 'next image' button that replaces the drop-down list. Select that, and it will load the next image in, until you run out of images (it will display a warning) and you can upload more

**Comment by csherwood-usgs** [comment]
It would be nice to have a button to reset all of the sliders to the default value. I have lost track. Plus maybe somewhere an explanation of what each one does, and the effect of increasing/decreasing it. Maybe examples of images that needed specific values.
