### ISSUE TITLE
Suggestions/Questions/Breaking Dash attempts

### ISSUE THREAD

**Issue by jover-usgs** [Doodleverse/dash_doodler#3]
First off - this is SOO much more fun and intuitive to use than doodler, which was actually pretty great - so I am excited for this to develop further. 

In no particular order...will continue to play with it

0. Silly me followed your instructions step by step for the installation and launch and it took a message to Chris to realize you have to copy and paste the IP address rather than it automatically launching :) 

1. The code breaks if you delete/move the dash-default.jpg from the assets folder, which I did carelessly when moving and putting new images in for organizational purposes. Rename to DONTMOVEME or other workaround or just a little side note somewhere in the read me. 

2. I know you changed the way it is classifying the image - does dash care about the order of the classes? I know doodler did. 

3. If you zoom in on a section and change the pen size it zooms you right back out. Mildly annoying but very easy to work around if you know its going to happen. It also zooms you back out every time you finish doodling a small part, so it is not possible to doodle small discontinuous lines while zoomed in. Don't know if its easy to fix, but for those with poor eyesight the need to zoom and stay zoomed would be appreciated. 

4. The annotations .png in the results folder. What's going on there? Is it just showing where I drew? So difficult to see the thin lines on the blue. Same for the grayscale.png, it is just a black png.

5. Do photosets in the assets learn off of each other? I ask because I labeled a photo with the four water classes, got a segmentation, moved onto the next photo which only had two classes present, but when segmented it gave me small sections that were the other two non-present classes. Any way to nix that or is it a part of the segmentation. 

6. The class imbalance is tricky - I think anyone using this tool would benefit from the tips and tricks you have on your doodler page, for such stuff as corners, class islands, etc. Anything to help the learning curve.

**Comment by MARDAScience** [comment]
thanks for the report!

0. thanks I'll try to reminder to add that to the docs when i write them.
1. i found another workaround today. actively working on this!
2. im trying to fix annoying bugs associated with this. in short, yes. dealing with the classes and propagating them through all the workflows is really tough, in the original and in this version. the toughest part, easily. hold fire i have fixes coming
3. outside of my control entirely. use smaller images
4. yes thats for me, not for you
5. no learning from each other. that's a bug related to 2. right now, i cant figure out how to deal with this situation, working on it literally all day
6. yep, documentation forthcoming. perhaps i'll call upon you to help me write it ;)

**Comment by ddbuscombe** [comment]
Working on a fix for 2. and 5., hopefully tonight

**Comment by ddbuscombe** [comment]
Made some inroads into many of these issues, so closing for now ... I will use these suggestions in my next round of doc edits

**Comment by ddbuscombe** [comment]
@jin-si fyi, the next version will have a larger image window, so less zooming. some of the other issues are now gone. Some browsers will launch automatically, but I have added that detail in too. Keep the feedback coming!

**Comment by jover-usgs** [comment]
Amazing! And as to one of your previous comments - I would be happy to help write some of the documentation :)
