### ISSUE TITLE
Use standardized date format for results directories

### ISSUE THREAD

**Issue by dnowacki-usgs** [Doodleverse/dash_doodler#5]
Presently results from doodling are written to folders with the format "%d-%m-%Y-%H-%M-%S" (I guess this is British format? 😃).

https://github.com/dbuscombe-usgs/dash_doodler/blob/dc69107602f72238c2bfc9d1d0286a4198b08d99/app.py#L94-L100

This has the disadvantage that dates do not sort by name when viewing a directory listing. I suggest switching to a more [ISO-ish](https://en.wikipedia.org/wiki/ISO_8601) format like "%Y-%m-%d-%H-%M-%S". This would sort correctly in a time/alphabetical sense. Happy to submit a PR if you're into this idea.

**Comment by ddbuscombe** [comment]
Good suggestion, thanks, wasn't thinking. I'll incorporate in next round of edits

**Comment by ddbuscombe** [comment]
This is now incorporated. Thanks again
