### ISSUE TITLE
Pull-down file menu is munted

### ISSUE THREAD

**Issue by csherwood-usgs** [Doodleverse/dash_doodler#6]
I get this same problem Firefox, Chrome, and MS Edge. Fonts overlap and vibrates. Hard to select a file...but seems like everything works after that.

![image](https://user-images.githubusercontent.com/1618995/97997284-cddd0700-1db6-11eb-9164-fea095d5aeae.png)

**Comment by ddbuscombe** [comment]
To accommodate these long file names that wrap over into multiple rows, increase the height of the rows. In `app.py`, change this line `optionHeight=15,` to a larger number

**Comment by csherwood-usgs** [comment]
I set it to 25, but the real problem is the width of the box. I had a side tab open in my browser...when I closed that, the app got more screen space and the names fit in the dropdown box, and the problem went away. 

So I tried changing the font size. That worked:
Starting at line 251: 
```
                html.Div(
                       id="right-column",
                       style={'fontSize': 12},
                       children=[
```
And now the image filenames fit comfortably.

**Comment by ddbuscombe** [comment]
Ok. Glad you found a fix. I'm not inclined to make this fix default because the real issue is actually long file names, and me wanting to preserve as much real estate on screen for doodling as possible (because of the bigger issues with zoom). So, I will keep the width of the box as is, and if anyone has really long filenames, I will point them to this fix. Thanks

**Comment by csherwood-usgs** [comment]
Making the font smaller does not increase the width of the box...it just allows the filenames to fit in the existing width.

**Comment by ddbuscombe** [comment]
Understood.

**Comment by ddbuscombe** [comment]
No fixable issue here. Change the fontsize if you have really long file names
