### ISSUE TITLE
Zoom does not hold

### ISSUE THREAD

**Issue by csherwood-usgs** [Doodleverse/dash_doodler#7]
When I zoom in  using a box and then pick a class to doodle, it zooms back out. When I use the +/- icons to zoom, then pan, then pick the drawing tool, I get to draw one line, then it zooms back out. Any way to turn of automatic zooming?

**Comment by ddbuscombe** [comment]
Been trying to figure this one out. Will have another look at this issue today. I may end up enforcing no zoom, to make sure people use smaller imagery. Zooming in and out is really time consuming

**Comment by ddbuscombe** [comment]
zoom does work and takes some getting used to ... see this blog post https://dbuscombe-usgs.github.io/dash_doodler/blog/2021/07/08/Doodler-Zoom

closing for now
